//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDMG.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dungeon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dungeon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDMG.Resources.Dungeon", typeof(Dungeon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add dungeon.
        /// </summary>
        public static string AddDungeon {
            get {
                return ResourceManager.GetString("AddDungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a theme.
        /// </summary>
        public static string ChooseTheme {
            get {
                return ResourceManager.GetString("ChooseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corridors.
        /// </summary>
        public static string Corridor {
            get {
                return ResourceManager.GetString("Corridor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create dungeon.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead ends.
        /// </summary>
        public static string DeadEnd {
            get {
                return ResourceManager.GetString("DeadEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon count.
        /// </summary>
        public static string DungeonCount {
            get {
                return ResourceManager.GetString("DungeonCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon difficulty.
        /// </summary>
        public static string DungeonDifficulty {
            get {
                return ResourceManager.GetString("DungeonDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon size.
        /// </summary>
        public static string DungeonSize {
            get {
                return ResourceManager.GetString("DungeonSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate dungeon.
        /// </summary>
        public static string GenerateDungeon {
            get {
                return ResourceManager.GetString("GenerateDungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate plain map.
        /// </summary>
        public static string GeneratePlainMap {
            get {
                return ResourceManager.GetString("GeneratePlainMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items max rarity.
        /// </summary>
        public static string ItemsRarity {
            get {
                return ResourceManager.GetString("ItemsRarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal.
        /// </summary>
        public static string Minimal {
            get {
                return ResourceManager.GetString("Minimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monsters type.
        /// </summary>
        public static string MonsterType {
            get {
                return ResourceManager.GetString("MonsterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New dungeon name.
        /// </summary>
        public static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party level.
        /// </summary>
        public static string PartyLevel {
            get {
                return ResourceManager.GetString("PartyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party size.
        /// </summary>
        public static string PartySize {
            get {
                return ResourceManager.GetString("PartySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename dungeon.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roaming monsters.
        /// </summary>
        public static string RoamingPercent {
            get {
                return ResourceManager.GetString("RoamingPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room density.
        /// </summary>
        public static string RoomDensity {
            get {
                return ResourceManager.GetString("RoomDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room size.
        /// </summary>
        public static string RoomSize {
            get {
                return ResourceManager.GetString("RoomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dungeon.
        /// </summary>
        public static string ShowDungeon {
            get {
                return ResourceManager.GetString("ShowDungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dungeons.
        /// </summary>
        public static string ShowDungeons {
            get {
                return ResourceManager.GetString("ShowDungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub dungeons.
        /// </summary>
        public static string SubDungeons {
            get {
                return ResourceManager.GetString("SubDungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeons.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traps.
        /// </summary>
        public static string TrapPercent {
            get {
                return ResourceManager.GetString("TrapPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure value.
        /// </summary>
        public static string TreasureValue {
            get {
                return ResourceManager.GetString("TreasureValue", resourceCulture);
            }
        }
    }
}
